### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by CelestialTheWolffo** [Dan12/Launchpad#18]
Ok, so ive checked my sound and its not my laptop, whenever i press a key it doesnt make any sound. It still shows the key being pressed though... its not working and ive been trying to get it work all day. I even restarted my laptop : ( please fix this :(

**Comment by Dan12** [comment]
You may have to clear your browser cache.

**Comment by Impy7** [comment]
I cleared my browser cache, but the sound isn't working... any suggest?

**Comment by Impy7** [comment]
sound works with all sites

**Comment by timoosh** [comment]
yeah not working for me ether even after the cash clear

**Comment by Dan12** [comment]
The new Google Chrome update has made my website incompatible with the new changes (https://developers.google.com/web/updates/2017/09/autoplay-policy-changes). I will try and fix them shortly. If you want to use the site while this is still broken, try using a different browser.

**Comment by Dan12** [comment]
Update: this issue should now be fixed on the newest version of the Google Chrome browser.
