### ISSUE TITLE
No Sounds 

### ISSUE THREAD

**Issue by Akpshi** [Dan12/Launchpad#19]
yesterday it was working but today it isn't working everytime i tap a letter there's no sound which make's me really sad please fix this and i will be really happy.

**Comment by Dan12** [comment]
The new Google Chrome update has made my website incompatible with the new changes (https://developers.google.com/web/updates/2017/09/autoplay-policy-changes). I will try and fix them shortly. If you want to use the site while this is still broken, try using a different browser.

**Comment by Dan12** [comment]
Update: this issue should now be fixed on the newest version of the Google Chrome browser.
