### ISSUE TITLE
Doesn't load

### ISSUE THREAD

**Issue by MRxDOUGHNUTXMAN** [Dan12/Launchpad#4]
the past 3 weeks I have been trying to load the launch pad but it either says there is an error, or it just never loads. I used to use this all the time with no issues, so it's sad to see it not working.

**Comment by Dan12** [comment]
One fix I've found: clear your web browser cache.
If that doesn't work, please report the browser you are using and a few more details about the issues you are seeing.

**Comment by MRxDOUGHNUTXMAN** [comment]
ahhh yes that one worked. Thanks not really sure why I didn't think of that lol. any who have a great day!
